/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AlumnoT
 */
public class BurguerBBDD extends javax.swing.JFrame {

    /**
     * Creates new form BurguerBBDD
     */
    public BurguerBBDD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hamburguesaGroup = new javax.swing.ButtonGroup();
        panGroup = new javax.swing.ButtonGroup();
        papasGroup = new javax.swing.ButtonGroup();
        bebidasGroup = new javax.swing.ButtonGroup();
        repartoGroup = new javax.swing.ButtonGroup();
        tituloMenu = new javax.swing.JLabel();
        localRadio = new javax.swing.JRadioButton();
        domicilioRadio = new javax.swing.JRadioButton();
        pedirButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        vegana = new javax.swing.JRadioButton();
        cerdo = new javax.swing.JRadioButton();
        ternera = new javax.swing.JRadioButton();
        hamburguesaLabel = new javax.swing.JLabel();
        pollo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        panCenteno = new javax.swing.JRadioButton();
        panLabel = new javax.swing.JLabel();
        panIntegral = new javax.swing.JRadioButton();
        panNormal = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        caseras = new javax.swing.JRadioButton();
        fritas = new javax.swing.JRadioButton();
        patatasLabel = new javax.swing.JLabel();
        gajo = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        colaButton = new javax.swing.JRadioButton();
        cerveButton = new javax.swing.JRadioButton();
        limonButton = new javax.swing.JRadioButton();
        bebidaLabel = new javax.swing.JLabel();
        naranjaButton = new javax.swing.JRadioButton();
        aguaButton = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        mostLabel = new javax.swing.JLabel();
        thaiLabel = new javax.swing.JLabel();
        ketchupSpinner = new javax.swing.JSpinner();
        bbqSpinner = new javax.swing.JSpinner();
        ketLabel = new javax.swing.JLabel();
        thaiSpinner = new javax.swing.JSpinner();
        mostazaSpinner = new javax.swing.JSpinner();
        salsasLabel = new javax.swing.JLabel();
        bbqLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        quesoCheck = new javax.swing.JCheckBox();
        extrasLabel = new javax.swing.JLabel();
        papasCheck = new javax.swing.JCheckBox();
        dobleCheck = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        pvpTextField = new javax.swing.JTextField();
        precioLabel = new javax.swing.JLabel();
        precioTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ivaTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        tituloMenu.setText("Menu basico (8€):");

        repartoGroup.add(localRadio);
        localRadio.setText("Reparto a domicilio");

        repartoGroup.add(domicilioRadio);
        domicilioRadio.setText("Recogida en local (-20% dto.)");
        domicilioRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioRadioActionPerformed(evt);
            }
        });

        pedirButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pedirButton.setText("PEDIR");
        pedirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        hamburguesaGroup.add(vegana);
        vegana.setText("Vegana (+1€)");

        hamburguesaGroup.add(cerdo);
        cerdo.setText("Cerdo");

        hamburguesaGroup.add(ternera);
        ternera.setText("Ternera (+1€)");

        hamburguesaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hamburguesaLabel.setText("Hamburguesa");

        hamburguesaGroup.add(pollo);
        pollo.setText("Pollo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pollo)
                    .addComponent(ternera)
                    .addComponent(cerdo)
                    .addComponent(hamburguesaLabel)
                    .addComponent(vegana))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hamburguesaLabel)
                .addGap(5, 5, 5)
                .addComponent(pollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ternera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vegana)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panGroup.add(panCenteno);
        panCenteno.setText("Centeno");

        panLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panLabel.setText("Pan");

        panGroup.add(panIntegral);
        panIntegral.setText("Integral");

        panGroup.add(panNormal);
        panNormal.setText("Normal");
        panNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panNormal)
                            .addComponent(panCenteno, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(panIntegral)
                            .addGap(5, 5, 5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(panLabel)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panLabel)
                .addGap(5, 5, 5)
                .addComponent(panNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panIntegral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panCenteno)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        papasGroup.add(caseras);
        caseras.setText("Caseras (+1€)");

        papasGroup.add(fritas);
        fritas.setText("Fritas");

        patatasLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patatasLabel.setText("Patatas");

        papasGroup.add(gajo);
        gajo.setText("Gajo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(patatasLabel)
                    .addComponent(fritas)
                    .addComponent(gajo)
                    .addComponent(caseras))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(patatasLabel)
                .addGap(5, 5, 5)
                .addComponent(fritas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caseras)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bebidasGroup.add(colaButton);
        colaButton.setText("Cola");

        bebidasGroup.add(cerveButton);
        cerveButton.setText("Cerveza");

        bebidasGroup.add(limonButton);
        limonButton.setText("Limon");

        bebidaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bebidaLabel.setText("Bebida");

        bebidasGroup.add(naranjaButton);
        naranjaButton.setText("Naranja");

        bebidasGroup.add(aguaButton);
        aguaButton.setText("Agua");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(colaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naranjaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(limonButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cerveButton)
                        .addGap(18, 18, 18)
                        .addComponent(aguaButton)
                        .addGap(24, 24, 24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(bebidaLabel)
                        .addGap(317, 317, 317))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bebidaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naranjaButton)
                    .addComponent(limonButton)
                    .addComponent(cerveButton)
                    .addComponent(aguaButton)
                    .addComponent(colaButton))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mostLabel.setLabelFor(mostazaSpinner);
        mostLabel.setText("Mostaza");

        thaiLabel.setLabelFor(thaiSpinner);
        thaiLabel.setText("Thai");

        ketLabel.setLabelFor(ketchupSpinner);
        ketLabel.setText("Ketchup");

        salsasLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salsasLabel.setText("Salsas (+0'50€ cada una)");

        bbqLabel.setLabelFor(bbqSpinner);
        bbqLabel.setText("BBQ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ketLabel)
                        .addGap(18, 18, 18)
                        .addComponent(thaiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salsasLabel)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostLabel)
                            .addComponent(bbqLabel)
                            .addComponent(thaiLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostazaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbqSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ketchupSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(salsasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketLabel)
                    .addComponent(thaiSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketchupSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostLabel))
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bbqSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbqLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mostazaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thaiLabel))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        quesoCheck.setText("Extra de queso (+0'50€)");

        extrasLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        extrasLabel.setText("Extras:");

        papasCheck.setText("Extra de patatas (+1€)");

        dobleCheck.setText("Doble (+2€)");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extrasLabel)
                    .addComponent(quesoCheck)
                    .addComponent(dobleCheck)
                    .addComponent(papasCheck))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(extrasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dobleCheck)
                .addGap(8, 8, 8)
                .addComponent(quesoCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(papasCheck)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        precioLabel.setText("PRECIO");

        jLabel2.setText("P.V.P");

        jLabel1.setText("IVA (21%)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioLabel))
                .addGap(66, 66, 66)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ivaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pvpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioLabel)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ivaTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pvpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tituloMenu)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(localRadio)
                                            .addComponent(domicilioRadio)
                                            .addComponent(pedirButton))
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tituloMenu)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(localRadio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(domicilioRadio)))
                .addGap(27, 27, 27)
                .addComponent(pedirButton)
                .addGap(34, 34, 34)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_panNormalActionPerformed
        
    
    double precio = 8;
    double iva;
    double pvp;
        
    
    
    private void pedirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirButtonActionPerformed
        
        
        if (ternera.isEnabled() || vegana.isEnabled()){
            precio = precio + 1;
        }
        if (caseras.isEnabled()){
            precio = precio + 1;
        }
        if (dobleCheck.isEnabled()){
            precio = precio + 2;
        }
        if (quesoCheck.isEnabled()){
            precio = precio + 0.5;
        }
        if (papasCheck.isEnabled()){
            precio = precio + 1;
        }
        precio = precio + (int)(ketchupSpinner.getValue());
        precio = precio + (int)(mostazaSpinner.getValue());
        precio = precio + (int)(bbqSpinner.getValue());
        precio = precio + (int)(thaiSpinner.getValue());
        
        iva = precio*0.21;
        pvp = iva+precio;
        
        precioTextField.setText(String.valueOf(precio));
        ivaTextField1.setText(String.valueOf(iva));
        pvpTextField.setText(String.valueOf(pvp));
 
    }//GEN-LAST:event_pedirButtonActionPerformed

    private void domicilioRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurguerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurguerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurguerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurguerBBDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurguerBBDD().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aguaButton;
    private javax.swing.JLabel bbqLabel;
    private javax.swing.JSpinner bbqSpinner;
    private javax.swing.JLabel bebidaLabel;
    private javax.swing.ButtonGroup bebidasGroup;
    private javax.swing.JRadioButton caseras;
    private javax.swing.JRadioButton cerdo;
    private javax.swing.JRadioButton cerveButton;
    private javax.swing.JRadioButton colaButton;
    private javax.swing.JCheckBox dobleCheck;
    private javax.swing.JRadioButton domicilioRadio;
    private javax.swing.JLabel extrasLabel;
    private javax.swing.JRadioButton fritas;
    private javax.swing.JRadioButton gajo;
    private javax.swing.ButtonGroup hamburguesaGroup;
    private javax.swing.JLabel hamburguesaLabel;
    private javax.swing.JTextField ivaTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel ketLabel;
    private javax.swing.JSpinner ketchupSpinner;
    private javax.swing.JRadioButton limonButton;
    private javax.swing.JRadioButton localRadio;
    private javax.swing.JLabel mostLabel;
    private javax.swing.JSpinner mostazaSpinner;
    private javax.swing.JRadioButton naranjaButton;
    private javax.swing.JRadioButton panCenteno;
    private javax.swing.ButtonGroup panGroup;
    private javax.swing.JRadioButton panIntegral;
    private javax.swing.JLabel panLabel;
    private javax.swing.JRadioButton panNormal;
    private javax.swing.JCheckBox papasCheck;
    private javax.swing.ButtonGroup papasGroup;
    private javax.swing.JLabel patatasLabel;
    private javax.swing.JButton pedirButton;
    private javax.swing.JRadioButton pollo;
    private javax.swing.JLabel precioLabel;
    private javax.swing.JTextField precioTextField;
    private javax.swing.JTextField pvpTextField;
    private javax.swing.JCheckBox quesoCheck;
    private javax.swing.ButtonGroup repartoGroup;
    private javax.swing.JLabel salsasLabel;
    private javax.swing.JRadioButton ternera;
    private javax.swing.JLabel thaiLabel;
    private javax.swing.JSpinner thaiSpinner;
    private javax.swing.JLabel tituloMenu;
    private javax.swing.JRadioButton vegana;
    // End of variables declaration//GEN-END:variables
    private String validarCampos(){
        return "";
    }

}
